project:
  type: book
  output-dir: docs

book:
  title: "R para el Análisis Estadístico de Datos Agrícolas"
  author: "P. Agr. Ludwing Isaí Marroquín Jiménez"
  output-file: "R_para_Analisis_Estadistico_Datos_Agricolas"
  date: 06/27/2025
  date-format: medium
  favicon: logo_cete_vector.png
  description: Manual práctico para el análisis estadístico de datos agrícolas utilizando R, orientado a estudiantes y profesionales de agronomía.
  keyword: R, Estadística, Agronomía, Análisis de datos, Reproducibilidad
  url: https://github.com/Ludwing-MJ/estadistica_agricola
  page-navigation: true
  sidebar:
    logo: logo_cete_vector.png
    search: true
    collapse-level: 4
  repo-subdir: book
  sharing: [twitter, linkedin]
  downloads: [pdf]
  image: logo_cete_vector.png

  page-footer:
    center:
      - text: "Licencia"
        href: license.qmd

  chapters:
    - index.qmd
    - C0.qmd
    - part: "Aspectos Introductorios"
    - C1.1.qmd
    - part: "Clasificación de variables"
    - C2.1.qmd
    - part: "Notación sumatoria"
    - C3.1.qmd
    - C3.2.qmd
    - C3.3.qmd
    - part: "Estadística descriptiva para datos sin agrupar"
    - C4.1.qmd
    - c4.2.qmd
    - c4.3.qmd
    - part: "Estadística descriptiva para datos agrupados"
    - C5.1.qmd
    - C5.2.qmd
    - C5.3.qmd
    - part: "Introducción a probabilidades"
    - C6.1.qmd
    - part: "Distribuciones de probabilidad discretas"
    - C7.1.qmd
    - part: "Distribución normal"
    - C8.1.qmd
    - part: "Intervalos de confianza"
    - C9.1.qmd
    - part: "Pruebas de hipótesis"
    - C10.1.qmd
    - part: "Regresión lineal y correlación"
    - C11.1.qmd
    - C11.2.qmd
    - part: "Referencias"
    - references.qmd

bibliography: references.bib
biblio-style: "apalike"

format:
  html:
    lang: es
    number-sections: true
    theme:
      light: flatly
      dark: cyborg
    css: custom.css
    number-depth: 4
    link-external-icon: true
    link-external-newwindow: true

  pdf:
    code-overflow: wrap
    lang: es
    documentclass: scrreprt
    classoption: ["onepage", "openany"]
    papersize: a4
    toc: true
    margin-top: 30mm
    margin-left: 30mm
    margin-bottom: 30mm
    margin-right: 30mm
    titlepage-geometry:
      - top=30mm
      - bottom=30mm
      - right=30mm
      - left=30mm
    include-in-header:
      text: |
        \usepackage{hanging}
        \renewcommand{\partname}{Capítulo} % Cambia "Part" por "Capítulo"

editor: visual