project:
  type: book
  output-dir: docs

book:
  title: "R para el Análisis Estadístico de Datos Agrícolas"
  author: "P. Agr. Ludwing Isaí Marroquín Jiménez"
  output-file: "R para el Análisis Estadístico de Datos Agrícolas"
  date: "2025-06-27" # Formato YYYY-MM-DD es más estándar
  date-format: medium
  favicon: logo_cete_vector.png
  page-navigation: true
  sidebar:
    logo: logo_cete_vector.png # Logo presente en el libro
    search: true
    collapse-level: 4
  chapters:
    - index.qmd
    - C0.qmd
    - part: "1. Aspectos Introductorios"
      attributes:
        class: part
    - C1.1.qmd
    - part: "2. Clasificación de variables"
      attributes:
        class: part
    - C2.1.qmd
    - part: "3. Notación sumatoria"
      attributes:
        class: part
    - C3.1.qmd
    - part: "4. Medidas de tendencia central y dispersión (datos no agrupados)"
      attributes:
        class: part
    - C4.1.qmd
    - part: "5. Medidas de tendencia central y dispersión (datos agrupados)"
      attributes:
        class: part
    - C5.1.qmd
    - part: "6. Introducción a probabilidades"
      attributes:
        class: part
    - C6.1.qmd
    - part: "7. Distribuciones de probabilidad discretas"
      attributes:
        class: part
    - C7.1.qmd
    - part: "8. Distribución normal"
      attributes:
        class: part
    - C8.1.qmd
    - part: "9. Intervalos de confianza"
      attributes:
        class: part
    - C9.1.qmd
    - part: "10. Pruebas de hipótesis"
      attributes:
        class: part
    - C10.1.qmd
    - part: "11. Regresión lineal y correlación"
      attributes:
        class: part
    - C11.1.qmd
    - part: "Referencias"
      attributes:
        class: part
    - references.qmd

bibliography: references.bib

repo-subdir: book
sharing: [twitter, linkedin]
downloads: [pdf]
image: logo_cete_vector.png

format:
  html:
    lang: es
    number-sections: false # Deshabilitar la numeración global
    theme:
      light: flatly
      dark: cyborg
    css: custom.css
    number-depth: 4
    link-external-icon: true
    link-external-newwindow: true

  pdf:
    code-overflow: wrap
    lang: es
    documentclass: scrreprt
    classoption: ["onepage", "openany"]
    papersize: a4
    toc: true
    margin-top: 30mm
    margin-left: 30mm
    margin-bottom: 30mm
    margin-right: 30mm
    titlepage-geometry:
      - top=30mm
      - bottom=30mm
      - right=30mm
      - left=30mm
    include-in-header:
      text: |
        \usepackage{hanging}
        \renewcommand{\partname}{Capítulo} # Cambia "Part" por "Capítulo"

editor: visual